### ISSUE TITLE
Error when training the model

### ISSUE THREAD

**Issue by Blowdire** [SapienzaNLP/extend#10]
Hi, I have tried to train the model with the command you provided 
`classy train qa ./Datasets/aida -n my-model-name --profile aida-longformer-large-gam -pd extend`

I have also prepared the training data with the right name and extension, but the command gives me this error 
`Traceback (most recent call last):
  File "/opt/miniconda3/envs/extend/bin/classy", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/classy/scripts/cli/__init__.py", line 141, in main
    import_module_and_submodules(to_import)
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/classy/scripts/cli/utils.py", line 201, in import_module_and_submodules
    import_module_and_submodules(subpackage, exclude=exclude)
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/classy/scripts/cli/utils.py", line 201, in import_module_and_submodules
    import_module_and_submodules(subpackage, exclude=exclude)
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/classy/scripts/cli/utils.py", line 190, in import_module_and_submodules
    module = importlib.import_module(package_name)
  File "/opt/miniconda3/envs/extend/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/agazzi/extend/extend/demo/serve.py", line 2, in <module>
    import spacy
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 8, in init spacy.pipeline.pipe
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/spacy/training/__init__.py", line 11, in <module>
    from .callbacks import create_copy_from_base_model  # noqa: F401
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/spacy/training/callbacks.py", line 3, in <module>
    from ..language import Language
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/spacy/language.py", line 25, in <module>
    from .training.initialize import init_vocab, init_tok2vec
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/spacy/training/initialize.py", line 14, in <module>
    from .pretrain import get_tok2vec_ref
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/spacy/training/pretrain.py", line 16, in <module>
    from ..schemas import ConfigSchemaPretrain
  File "/opt/miniconda3/envs/extend/lib/python3.9/site-packages/spacy/schemas.py", line 216, in <module>
    class TokenPattern(BaseModel):
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 451, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 545, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 550, in pydantic.fields.ModelField._type_analysis
  File "/opt/miniconda3/envs/extend/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class`

**Comment by maosl2000** [comment]
Hello, I encountered the same issue. Have you managed to resolve it?

**Comment by edobobo** [comment]
Hey, sorry for the late response. Did you use the `setup.sh` script to set up your environment?
